import 'package:flutter/material.dart';

// A map of icon names to their corresponding Material icon data.
final Map<String, IconData> appIcons = {
  'menu_book_rounded': Icons.menu_book_rounded,
  'medication_rounded': Icons.medication_rounded,
  'account_balance_wallet_rounded': Icons.account_balance_wallet_rounded,
  'watch_rounded': Icons.watch_rounded,
  'map_rounded': Icons.map_rounded,
  'emoji_nature_rounded': Icons.emoji_nature_rounded,
  'battery_charging_full_rounded': Icons.battery_charging_full_rounded,
  'remove_red_eye_rounded': Icons.remove_red_eye_rounded,
  'headset_rounded': Icons.headset_rounded,
  'checkroom_rounded': Icons.checkroom_rounded,
  'bedtime_rounded': Icons.bedtime_rounded,
  'all_inbox_rounded': Icons.all_inbox_rounded,
  'directions_run_rounded': Icons.directions_run_rounded,
  'accessibility_new_rounded': Icons.accessibility_new_rounded,
  'emoji_people_rounded': Icons.emoji_people_rounded,
  'pool_rounded': Icons.pool_rounded,
  'dry_cleaning_rounded': Icons.dry_cleaning_rounded,
  'healing_rounded': Icons.healing_rounded,
  'local_florist_rounded': Icons.local_florist_rounded,
  'opacity_rounded': Icons.opacity_rounded,
  'grain_rounded': Icons.grain_rounded,
  'ac_unit_rounded': Icons.ac_unit_rounded,
  'content_cut_rounded': Icons.content_cut_rounded,
  'electric_bolt_rounded': Icons.electric_bolt_rounded,
  'brush_rounded': Icons.brush_rounded,
  'shower_rounded': Icons.shower_rounded,
  'icecream_rounded': Icons.icecream_rounded,
  'clean_hands_rounded': Icons.clean_hands_rounded,
  'link_rounded': Icons.link_rounded,
  'laptop_rounded': Icons.laptop_rounded,
  'laptop_mac_rounded': Icons.laptop_mac_rounded,
  'tablet_rounded': Icons.tablet_rounded,
  'phone_iphone_rounded': Icons.phone_iphone_rounded,
  'keyboard_rounded': Icons.keyboard_rounded,
  'mouse_rounded': Icons.mouse_rounded,
  'camera_alt_rounded': Icons.camera_alt_rounded,
  'battery_std_rounded': Icons.battery_std_rounded,
  'camera_rounded': Icons.camera_rounded,
  'sd_card_rounded': Icons.sd_card_rounded,
  'trip_origin_rounded': Icons.trip_origin_rounded,
  'radio_button_checked_rounded': Icons.radio_button_checked_rounded,
  'cleaning_services_rounded': Icons.cleaning_services_rounded,
  'wb_sunny_rounded': Icons.wb_sunny_rounded,
  'beach_access_rounded': Icons.beach_access_rounded,
  'directions_walk_rounded': Icons.directions_walk_rounded,
  'phone_android_rounded': Icons.phone_android_rounded,
  'fitness_center_rounded': Icons.fitness_center_rounded,
  'spa_rounded': Icons.spa_rounded,
  'lock_rounded': Icons.lock_rounded,
  'water_drop_rounded': Icons.water_drop_rounded,
  'food_bank_rounded': Icons.food_bank_rounded,
  'sports_gymnastics_rounded': Icons.sports_gymnastics_rounded,
  'vpn_key_rounded': Icons.vpn_key_rounded,
  'pan_tool_rounded': Icons.pan_tool_rounded,
  'tire_repair_rounded': Icons.tire_repair_rounded,
  'build_rounded': Icons.build_rounded,
  'bolt_rounded': Icons.bolt_rounded,
  'cloudy_snowing': Icons.cloudy_snowing,
  'backpack_rounded': Icons.backpack_rounded,
  'explore_rounded': Icons.explore_rounded,
  'bug_report_rounded': Icons.bug_report_rounded,
  'downhill_skiing_rounded': Icons.downhill_skiing_rounded,
  'snowboarding_rounded': Icons.snowboarding_rounded,
  'anchor_rounded': Icons.anchor_rounded,
  'business_center_rounded': Icons.business_center_rounded,
};

/// Returns an [IconData] for a given icon name string.
///
/// Falls back to a default icon if the name is not found in the map.
IconData getIconByName(String name) {
  return appIcons[name] ?? Icons.help_outline_rounded; // Default fallback icon
}
